WASTE_INFO = {
    'E-Waste': {
        'examples': 'Phones, chargers, small appliances, and circuit boards.',
        'about': 'Electronic items can contain recoverable metals alongside components that need careful handling.',
        'danger': 'High',
        'danger_note': 'Batteries and electronic components may contain hazardous substances. Do not dismantle or burn them.',
        'decomposition': 'Can persist for decades or longer, depending on materials and conditions.',
        'impact': 'Informal dumping or burning can expose people and the environment to harmful substances while wasting recoverable materials.',
        'disposal': 'Keep the item intact and dry. Store damaged batteries separately, away from heat. Use a designated electronics take-back or collection service; do not place it in household recycling.',
        'recycling': 'Specialist recyclers can safely separate reusable components and recover metals such as copper and aluminium.',
        'reuse': 'If it still works, consider repair, resale, or donation through a trusted programme. Remove personal data before handing over a device.',
        'agriculture': 'Not suitable for composting or agricultural use.',
        'fact': 'Retired phones, chargers, and small appliances are worth setting aside for a dedicated electronics collection route.',
    },
    'General': {
        'examples': 'Mixed or contaminated packaging and items that do not fit other categories.',
        'about': 'General waste is a residual category for items that cannot currently be sorted into a more useful stream.',
        'danger': 'Low to moderate',
        'danger_note': 'Risk depends on what is mixed in. Check for batteries, chemicals, sharps, or other hazardous contents before handling.',
        'decomposition': 'Varies widely by material; some components may persist for many years.',
        'impact': 'Residual waste uses disposal capacity and may release pollution or greenhouse gases as it breaks down.',
        'disposal': 'Separate any recyclable, organic, or hazardous parts first. Bag the remaining residue and use your local council or community collection service.',
        'recycling': 'There is no single recycling route for mixed residual waste. Separating materials at source gives more items a chance of recovery.',
        'reuse': 'Check whether the item can be repaired, repurposed, or safely passed on before disposal.',
        'agriculture': 'Not suitable for composting unless the item is confirmed to be clean, untreated organic material.',
        'fact': 'Separating food scraps, sachet film, and dry packaging at home can make each stream easier to handle.',
    },
    'Glass': {
        'examples': 'Drink bottles, jars, and glass containers.',
        'about': 'Glass can be recycled repeatedly without losing its basic material quality when it is collected and sorted correctly.',
        'danger': 'Moderate',
        'danger_note': 'Broken edges can cause serious cuts. Do not put loose broken glass in a bag or recycling bin.',
        'decomposition': 'Does not readily biodegrade and may remain in the environment for a very long time.',
        'impact': 'Discarded glass occupies space and can injure people or animals, while clean separated glass can replace some virgin raw material.',
        'disposal': 'Reuse intact bottles when practical. Rinse containers and keep them separate. Wrap broken pieces securely, label them clearly, and follow local collection guidance.',
        'recycling': 'Collected glass is sorted by type and colour, crushed, and used as feedstock for new containers or other glass products where facilities exist.',
        'reuse': 'Use intact jars for storage or refillable bottles where safe and practical.',
        'agriculture': 'Not suitable for composting. Do not spread crushed glass on soil.',
        'fact': 'Where a supplier accepts returns, intact drink bottles can often be reused instead of discarded.',
    },
    'Hazardous': {
        'examples': 'Pesticides, solvents, paint, chemicals, medical sharps, and some batteries.',
        'about': 'Hazardous waste may be toxic, corrosive, flammable, infectious, or reactive and needs a controlled handling route.',
        'danger': 'High',
        'danger_note': 'Avoid direct contact, fumes, mixing, or pouring contents into drains. Keep away from children, animals, heat, and food.',
        'decomposition': 'Depends on the substance; some chemicals persist and can spread through soil or water.',
        'impact': 'Incorrect disposal can cause poisoning, fires, injury, and contamination of soil or water.',
        'disposal': 'Keep the substance in its original, closed container when safe. Do not mix products or pour them away. Contact your local environmental or waste authority for a suitable collection route. For an immediate exposure or spill, contact emergency services.',
        'recycling': 'Only specialist facilities should determine whether components can be recovered or require treatment.',
        'reuse': 'Do not reuse chemical or medical containers for food or household storage.',
        'agriculture': 'Never apply hazardous waste to crops, soil, or compost.',
        'fact': 'Pesticide containers and used batteries can enter household rubbish unnoticed, so keep them separate and labelled.',
    },
    'Metal': {
        'examples': 'Aluminium drink cans, steel tins, cookware, and clean scrap metal.',
        'about': 'Many common metals can be recovered and recycled, reducing the need to extract and process new raw materials.',
        'danger': 'Low to moderate',
        'danger_note': 'Sharp edges and heavy objects can cause injury. Handle scrap carefully and keep it away from children.',
        'decomposition': 'Does not biodegrade; corrosion rates vary with the metal and local conditions.',
        'impact': 'Dumped metal can persist and create injury risks. Recovery can conserve raw materials and production energy.',
        'disposal': 'Empty and rinse food containers. Keep sharp edges protected. Separate clean cans and scrap for a reputable collector or local recycling programme.',
        'recycling': 'Sorted metal is processed and remade into metal products. Keep it free of food, liquids, and attached hazardous parts.',
        'reuse': 'Reuse sturdy containers for non-food storage only when clean and safe; repair metal household items where practical.',
        'agriculture': 'Not suitable for composting. Do not bury scrap metal in garden soil.',
        'fact': 'Clean, sorted scrap is easier for local materials collectors to identify and recover.',
    },
    'Organic': {
        'examples': 'Fruit peels, vegetable scraps, leftover plant foods, and garden cuttings.',
        'about': 'Organic waste can return nutrients to soil when it is composted under suitable conditions.',
        'danger': 'Low',
        'danger_note': 'Store food scraps covered and away from pests. Exclude chemicals, batteries, and other non-organic items.',
        'decomposition': 'Often weeks to months in a well-managed compost system; conditions and material size affect the time.',
        'impact': 'Organic waste mixed into dumpsites can generate methane and leachate. Separating it creates an opportunity for composting.',
        'disposal': 'Keep scraps separate from plastics and other rubbish. Add suitable plant-based waste to a managed compost pile or local organic collection. Follow local rules for meat, dairy, and oils.',
        'recycling': 'Composting or anaerobic digestion can turn suitable organic material into soil amendment or biogas.',
        'reuse': 'Use suitable fruit and vegetable scraps in stocks or other recipes before composting, if they are still safe to eat.',
        'agriculture': 'Finished, mature compost can improve soil structure. Do not apply fresh or contaminated waste directly to crops.',
        'fact': 'Peels from yam, cassava, and plantain are familiar kitchen scraps that can be kept separate for suitable composting.',
    },
    'Paper': {
        'examples': 'Cardboard cartons, newspapers, office paper, and paper bags.',
        'about': 'Clean, dry paper fibres can be recovered into new paper products, though fibres shorten with repeated recycling.',
        'danger': 'Low',
        'danger_note': 'Paper is generally low risk. Keep it dry and away from flames; use care around heavily soiled or chemical-contaminated sheets.',
        'decomposition': 'Typically weeks to months in suitable conditions; coated or damp landfill material may behave differently.',
        'impact': 'Paper in dumpsites takes up space and can produce methane as it decomposes. Recycling can reduce demand for virgin fibre.',
        'disposal': 'Keep paper clean and dry, flatten boxes, and remove plastic film or tape where practical. Keep food-soiled or wax-coated paper out of paper recycling unless locally accepted.',
        'recycling': 'Paper is sorted, pulped, cleaned, and formed into new paper or cardboard products where collection and processing are available.',
        'reuse': 'Reuse one-sided sheets for notes or use sturdy boxes for storage before recycling.',
        'agriculture': 'Plain, uncoated paper can sometimes be added in small amounts to a managed compost pile. Avoid glossy, laminated, or contaminated paper.',
        'fact': 'Flattening cartons from shops and deliveries makes dry paper easier to store before collection.',
    },
    'Plastic': {
        'examples': 'Water sachets, PET drink bottles, food containers, and packaging.',
        'about': 'Plastic includes different resin types, so collection and recycling options depend on the item and local facilities.',
        'danger': 'Moderate',
        'danger_note': 'Do not burn plastic. Smoke can contain harmful pollutants. Keep lightweight packaging from blowing into drains and waterways.',
        'decomposition': 'Can persist for decades to centuries; many plastics fragment rather than fully biodegrade.',
        'impact': 'Plastic litter can block drainage, harm wildlife, and break into small particles. Burning it creates avoidable air pollution.',
        'disposal': 'Empty and rinse containers when water use is reasonable. Separate clean bottles and rigid containers if locally collected. Keep sachets and films contained and check for a suitable drop-off route.',
        'recycling': 'Accepted plastics are sorted by type, cleaned, and processed into flakes or pellets for new products. Not every plastic is accepted by every collector.',
        'reuse': 'Refill safe, reusable containers where the product is designed for reuse. Avoid reusing single-use packaging for food if it is damaged or not food-safe.',
        'agriculture': 'Do not mix plastic into compost or spread it on farmland.',
        'fact': 'Used water sachets are a familiar plastic waste stream; check whether a nearby collector accepts flexible film.',
    },
    'Textile': {
        'examples': 'Clothing, fabric offcuts, shoes, curtains, and household linens.',
        'about': 'Textiles combine fibres, dyes, and trims, which can make recycling more difficult than simply sorting by appearance.',
        'danger': 'Low',
        'danger_note': 'Ordinary clean textiles are low risk. Keep mouldy, chemically contaminated, or wet items separate and handle with care.',
        'decomposition': 'Ranges from months for some natural fibres to decades or longer for many synthetic blends.',
        'impact': 'Discarded textiles use landfill space. Synthetic fibres may shed small plastic fibres during use and washing.',
        'disposal': 'Keep items clean and dry. Repair or donate wearable clothes through a trusted local organisation. Check with collectors before handing over damaged textiles.',
        'recycling': 'Some programmes sort, reuse, shred, or process textiles into wiping cloths, stuffing, or fibre products; availability varies.',
        'reuse': 'Mend garments, repurpose clean fabric for household tasks, or pass usable items to someone who needs them.',
        'agriculture': 'Do not compost synthetic or treated textiles. Only untreated natural fibres should be considered for composting where local guidance allows.',
        'fact': 'Mending and passing on wearable clothes can extend their useful life before they become waste.',
    },
}
