services:
  - type: web
    name: wastewise-ng
    env: python
    region: oregon
    plan: free
    pythonVersion: "3.12.7"
    buildCommand: "./build.sh"
    startCommand: "cd backend && gunicorn backend.wsgi:application"
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.12.7"
