# Generated by Django 6.1 on 2026-09-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_specific_item_to_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanrecord',
            name='specific_item',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='specific_item_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
